name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas numpy
    
    - name: Run pytest
      run: |
        pytest -xvs scripts/
    
    - name: Validate CSV files
      run: |
        python - <<EOF
import pandas as pd
import os
import sys

exit_code = 0
for csv_file in [f for f in os.listdir('data') if f.endswith('.csv')]:
    print(f'Validating {csv_file}')
    try:
        df = pd.read_csv(f'data/{csv_file}')
        print(f'  - {len(df)} rows')
        print(f'  - {len(df.columns)} columns')
        print(f'  - Columns: {df.columns.tolist()}')
        print(f'  - No errors found')
    except Exception as e:
        print(f'  - ERROR: {str(e)}')
        exit_code = 1
sys.exit(exit_code)
EOF
